# Generated by Django 3.1.4 on 2026-06-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='doi',
            field=models.CharField(blank=True, max_length=255, verbose_name='DOI'),
        ),
    ]
